name: CITSmart Enterprise 7
description: |
  CITSmart Enterprise
version: v7.0.7.31
category: ITSM
maintainer: kariston.sugimoto@citsmart.com
license: BSD
projectURL: https://git.planejamento.gov.br/00428968198/citsmart
