name: CITSmart 7
description: Citsmart 7 Enterprise 
version: 7
category: ITSM
maintainer: Kariston Goya Sugimoto <kariston.sugimoto@centralit.com.br>
license: GLPv2
projectURL: http://centraldeservicos/
